### PR TITLE
update manifest automatically

### PR DESCRIPTION
**Pull request by B-Naoufal**

### CODE REVIEW

**Review by pivilartisant — APPROVED** [review]

**Review by Thykof — CHANGES_REQUESTED** [review]
I think this will not solve our need, see https://github.com/massalabs/station-massa-wallet/issues/444#issuecomment-1625072218

**Comment by Thykof** [comment]
I am trying to test this. It doesn't work, I create a branch here https://github.com/massalabs/station-massa-wallet/tree/444-nathan but I am stuck: it creates a commit but the build workflow doesn't take it into account.

**Comment by Thykof** [comment]
So I have the idea to:
- a job that update the manifest, commit and push
- adding a step in the build job to update the manifest, with action https://github.com/marketplace/actions/os-specific-run and for sed on windows: with https://github.com/mbuilov/sed-windows/releases

@peterjah WDYT?

**Comment by peterjah** [comment]
> So I have the idea to:
> 
> * a job that update the manifest, commit and push
> * adding a step in the build job to update the manifest, with action https://github.com/marketplace/actions/os-specific-run and for sed on windows: with https://github.com/mbuilov/sed-windows/releases
> 
> @peterjah WDYT?
creating commits from CI is always a pain.. What i will do is just set the version in manifest before uploading release assets and leave a template value...
But most of the time the most efficient process is just to do the bump commit/or release commit to set the version manually...

**Comment by Thykof** [comment]
closing in favor of https://github.com/massalabs/station-massa-wallet/pull/626

**Pull request closed without merging**
