### PR TITLE
Uniform transfer prompt

### PR DESCRIPTION
**Pull request by Thykof**
Refactor the transfer coins feature so that it uses the same sign prompt

Old transfer prompt:
Screenshot 2023-10-23 at 19 29 13

new sign transfer prompt:
Screenshot 2023-10-23 at 19 29 57

### CODE REVIEW

**Comment by Thykof** [comment]
@longgamma-massa low priority, you can review the PR description to see if it fit the need

**Comment by longgamma-massa** [comment]
This wasn't approved in designs yet as I am aware. Which designs have you followed @Thykof?

**Comment by Thykof** [comment]
I have just reuse the already implemented designs for the sign transfer operation

**Comment by mazmassa** [comment]
There's a hell glitch in the icon. It's far to be central. I know it's not related to your changes but is something to add in the task list. ;)

Screenshot 2023-10-26 at 15 35 23

**Review by mazmassa — APPROVED** [review]

**Pull request merged**
