### PR TITLE
fix wallet image mac

### PR DESCRIPTION
**Pull request by mazmassa**
We are fixing the MacOs icon when building wallet

image

### CODE REVIEW

**Review by Thykof — DISMISSED** [review]
task file is not used in the CI, the production zip asset is build by the CI. Could you do the same thing in the build job? Otherwise it will work only in local with command `task build`.

**Comment by mazmassa** [comment]
> task file is not used in the CI, the production zip asset is build by the CI. Could you do the same thing in the build job? Otherwise it will work only in local with command `task build`.

Sure!
Just updated!

**Comment by Thykof** [comment]
workflow is in progress https://github.com/massalabs/station-massa-wallet/actions/runs/5348189015

**Comment by Thykof** [comment]
unfortunately it fails: https://github.com/massalabs/station-massa-wallet/actions/runs/5348189015/jobs/9697731207

wails command is not found in the CI

**Comment by gregLibert** [comment]
@longgamma-massa @Thykof @mazmassa Do we need that for the next milestone (pre-ICO) ?

**Comment by longgamma-massa** [comment]
> @longgamma-massa @Thykof @mazmassa Do we need that for the next milestone (pre-ICO) ?
@gregLibert 
Following the rule robustness > UX, other installation improvements have higher priority than this ticket. 
Suggestion: include it as Nice-to-have because it makes Massa Wallet more user friendly (and trusted) as an app, but it's less prior than obtaining Windows/Apple dev certificates.

**Comment by Thykof** [comment]
close in favor of https://github.com/massalabs/station-massa-wallet/pull/674

**Pull request closed without merging**
